repos:
  # Backend: Ruff (Linting & Formatting)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.5
    hooks:
      - id: ruff
        types_or: [python, pyi]
        args: [--fix]
      - id: ruff-format
        types_or: [python, pyi]

  # Frontend: Run ESLint
  - repo: local
    hooks:
      - id: eslint
        name: ESLint (Frontend)
        entry: npm run lint --prefix frontend
        language: system
        files: "\\.(js|jsx|ts|tsx)$"

  # Frontend: Run Prettier for Formatting
  - repo: local
    hooks:
      - id: prettier
        name: Prettier (Frontend)
        entry: npm run format --prefix frontend
        language: system
        files: "\\.(js|jsx|ts|tsx)$"
