services:

  postgres:
    image: postgres:latest
    container_name: backend_postgres
    env_file:
      - .envs/test/db.env
    volumes:
      - backend_postgres_volume:/var/lib/postgresql/data/

  server:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: test
    container_name: backend_api
    env_file:
      - .envs/test/api.env
      - .envs/test/db.env
    volumes:
      - ./:/code
    restart: always  
    depends_on:
      - postgres

volumes:  
  backend_postgres_volume:
