services:

  postgres:
    image: postgres:latest
    container_name: backend_postgres
    env_file:
      - .envs/local/db.env
    volumes:
      - backend_postgres_volume:/var/lib/postgresql/data/

  server:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: local
    container_name: backend_api
    ports:
      - "8000:8000"
    env_file:
      - .envs/local/api.env
      - .envs/local/db.env
    volumes:
      - ./:/code
    restart: always  
    depends_on:    
      - postgres

volumes:  
  backend_postgres_volume:
