# Generated by Django 5.0.7 on 2024-12-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_ts", models.DateTimeField(auto_now_add=True)),
                ("modified_ts", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LIVING_ROOM_FURNITURE", "Living Room Furniture"),
                            ("BEDROOM_FURNITURE", "Bedroom Furniture"),
                            ("DINING_ROOM_FURNITURE", "Dining Room Furniture"),
                            ("KITCHEN_FURNITURE", "Kitchen Furniture"),
                            ("OFFICE_FURNITURE", "Office Furniture"),
                            ("OUTDOOR_FURNITURE", "Outdoor Furniture"),
                            ("CHILDRENS_FURNITURE", "Children's Furniture"),
                            ("STORAGE_FURNITURE", "Storage Furniture"),
                            ("BATHROOM_FURNITURE", "Bathroom Furniture"),
                            ("ACCENT_FURNITURE", "Accent Furniture"),
                        ]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
